# Generated by Django 3.2.5 on 2021-07-23 06:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=50)),
                ('Created_Date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(blank=True, max_length=50)),
                ('Quantity', models.IntegerField(blank=True, default='0')),
                ('Receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('Receive_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('Issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('Created_Date', models.DateTimeField(auto_now=True)),
                ('Export_to_CSV', models.BooleanField(default=False)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
            ],
        ),
    ]
