# Generated by Django 3.2.5 on 2021-07-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210722_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.svg', null=True, upload_to='profile_pics/%Y/%m/%d'),
        ),
    ]
